### ISSUE TITLE
API supports querying trains within the next X minutes

### ISSUE THREAD

**Issue by gary-rafferty** [oisin/ierail#26]
We used to [filter trains](https://github.com/oisin/ierail/blob/master/lib/core_ext.rb#L4) based on parsing the time attribute, but the API now appears to support passing in the minutes as a parameter.

`http://api.irishrail.ie/realtime/realtime.asmx/getStationDataByNameXML?StationDesc=Bayside&NumMins=20`

**Comment by oisin** [comment]
Imma close this because it smells a bit after 4 years :D
